// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type EntityPhysics = {
  entityId: number,
  rbHandleIndex: number,
  rbHandleGeneration: number,
  coHandleIndex: number,
  coHandleGeneration: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EntityPhysics {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU32Type()),
      new ProductTypeElement("rbHandleIndex", AlgebraicType.createU32Type()),
      new ProductTypeElement("rbHandleGeneration", AlgebraicType.createU32Type()),
      new ProductTypeElement("coHandleIndex", AlgebraicType.createU32Type()),
      new ProductTypeElement("coHandleGeneration", AlgebraicType.createU32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EntityPhysics): void {
    EntityPhysics.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EntityPhysics {
    return EntityPhysics.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


